#########################################
# This is the base Docker file          #
# It includes the following containers: #
#  - Flask                              #
#  - MySQL                              #
#########################################

version: "3.9"
services:
    flask:
        container_name: cradle_flask
        build:
            context: ./server
        volumes:
            - flask_uploads:/uploads
        environment:
            PORT: 5000
            DB_HOSTNAME: cradle_mysql
            DB_PORT: 3306
            DB_NAME: cradle
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        depends_on: 
            - mysql
    mysql:
        container_name: cradle_mysql
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
            - mysql_logs:/var/log
            - "./:/etc/mysql/conf.d"
        environment:
            MYSQL_DATABASE: cradle
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    fluentbit:
        container_name: cradle_fluentbit
        image: fluent/fluent-bit:2.0.5
        volumes:
            - flask_uploads:/flask/logs:ro
            - mysql_logs:/mysql/logs:ro
            - ./fluentbit/logs:/output/
            - ./fluentbit/config:/fluent-bit/etc
            - ./fluentbit/config/fluent-${ENV:-local}.conf:/fluent-bit/etc/fluent-bit.conf

volumes:
    flask_uploads:
    mysql_data:
    mysql_logs:
