###################################################
# This is the deployment Docker file              #
#                                                 #
# It includes the following containers:           #
#  - Flask (extended, running using prod server)  #
#  - MySQL (extended)                             #
#  - Caddy                                        #
###################################################

version: "3.7"
services:
    flask:
        build:
            dockerfile: Dockerfile.deploy
        restart: always
        command: gunicorn -c ./prod/gunicorn.conf.py app:app
        volumes:
            - flask_logs:/var/log
    mysql:
        restart: always
    caddy:
        container_name: cradle_caddy
        build:
            context: .
            dockerfile: caddy/Dockerfile
        restart: always
        environment:
            - DOMAIN=${DOMAIN}
            - API_HOSTNAME=cradle_flask
        ports:
            - 80:80
            - 443:443

volumes:
    flask_logs: