# Used for deployment to a server where we are getting images from Docker Hub
# Overlay ontop of base config with:
#    $ export IMAGE_TEST="v2022-05-20.ABCD1234"
#    $ docker compose -f docker-compose.yml -f docker-compose.deploy.yml up -d
# Set IMAGE_TAG to the image desired, such as:
#     dev
#     staging
#     vYYYY-MM-DD.SHA
#                                                 
# It includes the following containers:           
#  - Flask (extended, running using prod server)  
#  - MySQL (extended)                             
#  - Caddy                                        

version: "3.9"
services:
    flask:
        image: drbfraser/cradle_platfrom-backend:$IMAGE_TAG
        restart: always
        command: gunicorn -c ./prod/gunicorn.conf.py app:app
        volumes:
            - flask_logs:/var/log
    mysql:
        restart: always
        volumes:
            - mysql_logs:/var/log
            - "./:/etc/mysql/conf.d"
    caddy:
        container_name: cradle_caddy
        image: drbfraser/cradle_platfrom-revproxy_frontend:$IMAGE_TAG
        build:
            context: .
            dockerfile: caddy/Dockerfile
        restart: always
        environment:
            - DOMAIN=${DOMAIN}
            - API_HOSTNAME=cradle_flask
        ports:
            - 80:80
            - 443:443
        volumes:
            - caddy_logs:/var/log
    fluentbit:
        container_name: cradle_fluentbit
        image: fluent/fluent-bit:2.0.5
        volumes:
            - flask_logs:/flask/logs:ro
            - caddy_logs:/caddy/logs:ro
            - mysql_logs:/mysql/logs:ro
            - ./fluentbit/logs:/output/
            - ./fluentbit/config:/fluent-bit/etc
            - ./fluentbit/config/fluent-${ENV:-local}.conf:/fluent-bit/etc/fluent-bit.conf
volumes:
    flask_logs:
    caddy_logs:
    mysql_logs: