Parameters:
  Environment:
    Type: String
    AllowedValues:
      - staging
      - prod
    Default: staging

Resources:
  CradleHighLoginAttemptAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment} Login Attempt Alarm"
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - arn:aws:sns:${AWS::Region}:${AWS::AccountId}:LoginAlarm
      InsufficientDataActions: []
      MetricName: UserLoginAttempts
      Namespace: !Sub "cradle_${Environment}/login_attempt"
      Statistic: Sum
      Dimensions: []
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing

